# -*- coding: utf-8 -*-
import re, os

p = r'c:\Users\Admin1\Documents\FastViewCloudService\upgrade-summary-2026\upgrade-summary-2026.html'
c = open(p, encoding='utf-8').read()
print('首行注释:', c.startswith('<!-- Generated by Trae Work -->'))
print('ends html:', c.rstrip().endswith('</html>'))
for tag in ['div', 'section', 'table', 'figure', 'pre', 'ul', 'ol']:
    o = len(re.findall('<' + tag + '[ >]', c))
    cl = len(re.findall('</' + tag + '>', c))
    print(tag, o, cl, 'OK' if o == cl else 'MISMATCH')
base = r'c:\Users\Admin1\Documents\FastViewCloudService\upgrade-summary-2026'
for rel in ['_shared/js/echarts.min.js', '_shared/js/mermaid.min.js',
            '_shared/fonts/CrimsonPro-Regular.ttf', 'assets/charts.js']:
    print(rel, 'EXIST' if os.path.exists(os.path.join(base, rel)) else 'MISSING')
mm = re.findall(r'<pre class="mermaid">(.*?)</pre>', c, re.S)
print('mermaid blocks:', len(mm))
for b in mm:
    print('  flowchart:', bool(re.search(r'flowchart\s+TD', b)),
          '| 引号平衡:', b.count('"') % 2 == 0)
print('size KB:', round(len(c.encode('utf-8')) / 1024, 1))
